### ISSUE TITLE
Licenseが記載されておりません。

### ISSUE THREAD

**Issue by dote-tomo-mic** [mtoukei/statbox2#114]
このリポジトリにはLicenseが見つかりませんでした。
お手数ですがこちらのコードはどのような利用が許可されておりますでしょうか？

**Comment by kenzkenz** [comment]
すみません。今、あたらしいSTATBOX2を作っているところで、そちらを公開する際にはライセンセス等の記載を行います。このリポジトリはプロポーザルのために一時的に作ったリポジトリのため、ライセンスの考慮がありませんでした。ライセンス表記はありませんが、自由に使っていただいてかまいません。

**Comment by dote-tomo-mic** [comment]
了解しました。
